trunk-version = "^0.21.14"  # Trunk version at the start of this project.
# Just remove above if you want to see if trunk can still build in a different version.

# https://trunkrs.dev/configuration/#build-section

[build]
target = "index.html"  # The index HTML file to drive the bundling process.
minify = "on_release"  # Control minification: can be one of: never, on_release, always
dist = "docs"  # the folder name can be used by GitHub Pages (if not using GitHub Actions)
public_url = "/"
# public_url = "/3D-Sorting-Visualizer/"

[serve]
no_autoreload = false  # Disable auto-reload of the web app.
